#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    arr = [str(arr_temp) for arr_temp in input().strip().split(' ')]
    print(' '.join(arr[::-1]))        
    
    
